#!/bin/bash
#SBATCH --time=30:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=3 # Here we set 3 CPU's for this task.
#SBATCH --job-name=mcmc_tiny
#SBATCH --output=matlab_mcmc_tinyx.index.out
#SBATCH --mem=40000
module load MATLAB/2017b-GCC-4.9.3-2.25
cd /home/p276009/micro_probing_ica_peregrine 
#matlab -nodisplay -r "how_to_use_mcmc_pRF(n_hemi, n_stim, n_roi);"
./how_to_micro_probing n_hemi n_stim n_roi
#mcc -m how_to_use_mc
